### ISSUE TITLE
Balena Raspberry Pi 3B Sound stuttering and noise Issue

### ISSUE THREAD

**Issue by magnus411** [balenalabs/balena-sound#148]
Hello! I just downloaded and set up my Raspberry Pi with BalenaOS. The problem is when I try to play a song. The music kind of stutters all the time, and when I try to pause or turn up the volume, it takes a couple of seconds before it happens. It also produces a lot of noise 

I have tried flashing the SDcard and installing it all again, but it still doesn't work and the music is unplayable because of all the stuttering.  I have also tried switching PSU

I don't know how I can fix it:( From what I can see: "Missing RTP packet:" is repeated a lot.

I Uploaded the logs from my BalenaCloud. 
[phillipsskaugum57_aged-dawn-06.04.20_22_37_02_(+0200).txt](https://github.com/balenalabs/balena-sound/files/4440728/phillipsskaugum57_aged-dawn-06.04.20_22_37_02_.%2B0200.txt)

**Comment by anaclumos** [comment]
I also have the same problem. Although the sound improved after switching my PSU to 5V 3A, the background white noise and noticable Airplay and Bluetooth lag persists. Also the volume is somewhat low even after setting the volume to max. I use 3B+.

**Comment by tmigone** [comment]
Hello @magnus411, quick question, are you using a Pi 3? This looks like you are hitting a known issue where WiFi and Bluetooth interfere with each other (see [here](https://github.com/balenalabs/balena-sound/blob/master/DeviceSupport.md), item 4).

@anaclumos, regarding your problems, can you expand a bit on background white noise? That is something I haven't seen yet. Is it always coming out? Could it be due to a bad audio cable? 
About lag, do you refer to a delay between playing and hearing the music?

**Comment by cflachen** [comment]
Hi all, I had the same stuttering problem on my 3B+. SInce I only have one device running balena-Sound, I decided to disable the multi-room feature (DISABLE_MULTI_ROOM = 1).
Now the sound is crystal clear and I only get a missing RTP packet every 10-20 minutes.
I can also play through Bluetooth from two devices simultaneously, which was completely chopping everything up before, while still using the multi-room feature.

**Comment by kostasoft** [comment]
Tell me, please, how to disable the built-in bluetooth module and instead connect an external USB dongle? I connected the dongle, probably it was even determined by the system, because the LED on the dongle blinked.
Maybe this will help to solve the problem with sound?

Where are the bluetooth settings in the BalenaOs system? And what needs to be changed?

**Comment by AlexProgrammerDE** [comment]
@kostasoft your dongle should work without any configuration due to this line:
https://github.com/balenalabs/balena-sound/blob/843db0d0fd661e1b09651897059ed3f211b9ff2c/bluetooth-audio/start.sh#L57

**Comment by tmigone** [comment]
Let's keep disusion about this in #62
