### ISSUE TITLE
feature request: Could we include multiple connections

### ISSUE THREAD

**Issue by kitovh** [balenalabs/balena-sound#24]
I'm trying to figure out if there would be a way to allow multiple bluetooth devices to connect at the same time. When playing music from all devices, it would just cue whatever comes next regardless of who requested it.

Best,

**Comment by chrisys** [comment]
@kitovh that wouldn't be possible with the bluetooth audio setup, as it's streaming literally just the audio over the bluetooth, it has no concept of what that audio is or when tracks begin and end. Perhaps it would be possible via another protocol though?

**Comment by AlexProgrammerDE** [comment]
In https://github.com/Arkq/bluez-alsa/issues/70 was this mentioned.

**Comment by AlexProgrammerDE** [comment]
@chrisys @kitovh i have just tested it on my RPI 4 1GB. My two connected android phones were able to play music. But if both devices play at the same time i get RTP errors. Maybe is this caused by the firmware, which cant handle so many packets. As long as only one device plays music is this ok. I will close for now. Feel free to reopen if you have still problems with it.
