### ISSUE TITLE
Issue with setting up Balena-Sound in own docker

### ISSUE THREAD

**Issue by MBMM89** [balenalabs/balena-sound#444]
Hi i followed this guide to set up Balena Sound in its own docker without using balenaOS and seem to be having trouble setting it up keep getting this from the service status any help please
guide: https://github/com/balenalabs/balena-sound/issue/54

\u25cf BalenaSound.service - Docker Compose Application Service
   Loaded: loaded (/etc/systemd/system/BalenaSound.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-05-02 20:19:09 BST; 687ms ago
  Process: 4726 ExecStart=/usr/bin/docker-compose up (code=exited, status=1/FAILURE)
 Main PID: 4726 (code=exited, status=1/FAILURE)

May 02 20:19:07 raspberrypi systemd[1]: Started Docker Compose Application Service.
May 02 20:19:09 raspberrypi docker-compose[4726]: Building audio
May 02 20:19:09 raspberrypi docker-compose[4726]: Step 1/4 : FROM balenablocks/audio:%%BALENA_MACHINE_NAME%%
May 02 20:19:09 raspberrypi docker-compose[4726]: Service 'audio' failed to build: invalid reference format
May 02 20:19:09 raspberrypi systemd[1]: BalenaSound.service: Main process exited, code=exited, status=1/FAILURE
May 02 20:19:09 raspberrypi systemd[1]: BalenaSound.service: Failed with result 'exit-code'.

**Comment by tmigone** [comment]
Hey @MBMM89 balenaSound has changed quite a bit since that guide you link was created. We added a lot of new features that require running balenaOS OR modifying the application code significantly. 

In this case the error you are getting is because docker doesn't know about the templating we do, specifically it can't find `balenablocks/audio:%%BALENA_MACHINE_NAME%%`. If you go through the balena pipeline the `%%BALENA_MACHINE_NAME%%` will get replaced with the machine name of your device, for example `balenablocks/audio:raspberry-pi`. 

Making the change yourself will put you through that error but I'm sure others will pop up as again at this point the project is tightly coupled with balenaOS. 

We recently built balenaHub which is now the easiest way of getting started with balenaOS, you can get balenaSound from there with very little steps: https://hub.balena.io/balenalabs/balenasound
