### ISSUE TITLE
Broken (404) URL in 01-getting-started.md

### ISSUE THREAD

**Issue by akaars** [balenalabs/balena-sound#550]
The "supported devices" link in the
balena-sound/blob/master/docs/01-getting-started.md 
document is pointing to a non-existing 
https://github.com/balenalabs/balena-sound/blob/master/docs/device-support
instead of 
https://github.com/balenalabs/balena-sound/blob/master/docs/06-device-support.md

**Comment by tmigone** [comment]
Links in the docs are formatted with our static generator tool in mind, so that they are correctly resolved on our official docs site: https://sound.balenalabs.io/docs

Unfortunately this means browsing the docs using GitHub is not ideal as links appear broken. This is something we want to change but haven't had the time to do so just yet.
